apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1-container
        image: antoniocapizzi95/terraform-deploy-test:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
