apiVersion: v1
kind: Service
metadata:
  name: microservice1-service
  namespace: default
spec:
  selector:
    app: microservice1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
